### ISSUE TITLE
Замечания по 4-5

### ISSUE THREAD

**Issue by sergey-shambir** [intmpg/ImageViewer#1]
- что означает поле `i` в Buttons.h? Название ничего не объясняет.
- названия функций в структуре Buttons должны содержать глагол, как требуется по соглашениям о кодировании
- что означает поле `array_size` в Buttons и почему нельзя просто использовать std::vector, как в PictureViewer?
- в PictureViewer есть поля dx, dy, их можно объединить в одно поле с помощью типа данных sf::Vector2f.
- в `PictureViewer::getImageVector` сравнения `if (file_name.rfind(str) != -1)` недостаточно, что если файл называется "1.png.txt"?
- функция PictureViewer::processEvents слишком велика и занимается посторонней задачей - передачей позиции мыши объектам Buttons при событии нажатия левой кнопки. Эту задачу следует выполнять в отдельной функции.

**Comment by intmpg** [comment]
Исправлено

**Comment by sergey-shambir** [comment]
Принято
